#Evaluate the property classifier on EDM
#Evaluate the trained property classifier on the samples generated by the trained EDM model
python eval_conditional_qm9.py --generators_path outputs/exp_cond_alpha --classifiers_path qm9/property_prediction/outputs/exp_class_alpha --property alpha  --iterations 100  --batch_size 100 --task edm
#To use a pre-trained generator and classifier model for alpha you can use the following arguments:  and 
python eval_conditional_qm9.py --generators_path outputs/exp_35_conditional_nf192_9l_alpha --classifiers_path qm9/property_prediction/outputs/exp_class_alpha --property alpha  --iterations 100  --batch_size 100 --task edm